@startuml dirStruct
title ディレクトリ構成図

salt

{
  {T
    + src
      ++ components 
        +++ layout
          ++++ layout.tsx | 全ての画面のレイアウト
          ++++ ErrorBoundary.tsx
        +++ atoms
        +++ molecules
          ++++ Header.tsx
          ++++ Footer.tsx
        +++ organisms
          ++++ ChangeSeat.tsx
          ++++ Setting.tsx
      ++ hooks | hooks 依存なし
      ++ api | supabaseと通信するロジックを書く
      ++ utils | ユーティリティ系
      ++ pages
        +++ _app.tsx 
        +++ _document.tsx 
        +++ Login.tsx | ログイン画面
        +++ index.tsx | トップページ、席替え画面表示
        +++ about.tsx | このサイトについて
        +++ usage.tsx | 使い方の説明など
        +++ setting.tsx | 席の設定ページ
      ++ styles
        +++ globals.css
  }
}

@enduml